### ISSUE TITLE
Add Mathematics Subject Classification (MSC2010)

### ISSUE THREAD

**Issue by nichtich** [bartoc-basel/skosmos-configuration#2]
RDF/XML SKOS file available at <http://msc2010.org/resources/MSC/2010/info/msc2010.skos> (I just updated this in <http://bartoc.org/en/node/474>). See http://msc2010.org/resources/MSC/2010/info/ for background.

**Comment by ALedl** [comment]
File is not valid, just a draft.

**Comment by nichtich** [comment]
Oh, the [MSC 2020](https://msc2020.org/) is already being discussed so nobody seems to have noticed or taken car of. To me the file looks valid and I would not be distracted by the word "draft".

**Comment by ALedl** [comment]
Skosify is not really happy with it:

Status: processing
Phase 1

Parsing input files
Warnings (7) show / hide full list

    http://msc2010.org/resources/MSC/2010/the classification number--03 in the other sections does not look like a valid URI, trying to serialize this will break.
    http://msc2010.org/resources/MSC/2010/32P05; see also 46S10 does not look like a valid URI, trying to serialize this will break.
    http://msc2010.org/resources/MSC/2010/also 46M20 does not look like a valid URI, trying to serialize this will break.

Phase 2

Performing inferences
Phase 3

Setting up namespaces
Phase 4

Transforming concepts, literals and relations
Warnings (2308) show / hide full list

    Stripping whitespace from label of http://msc2010.org/resources/MSC/2010/00A08: 'Recreational mathematics '
    Stripping whitespace from label of http://msc2010.org/resources/MSC/2010/00A08: 'Matematica ricreativa '
    Stripping whitespace from label of http://msc2010.org/resources/MSC/2010/00A30: 'Philosophy of mathematics '

Messages (12) show / hide full list

    Don't know what to do with type http://xmlns.com/foaf/0.1/Person
    Don't know what to do with type http://xmlns.com/foaf/0.1/Organization
    Don't know what to do with type http://xmlns.com/foaf/0.1/Group

Phase 5

Performing SKOS enrichments
Phase 6

Cleaning up
Phase 7

Setting up concept schemes and top concepts
Messages (2602) show / hide full list

    Marking loose concept http://msc2010.org/resources/MSC/2010/00A08-formerly-1991 as top concept of scheme http://msc2010.org/resources/MSC/2010/MSC2010
    Marking loose concept http://msc2010.org/resources/MSC/2010/00A30-formerly-1991 as top concept of scheme http://msc2010.org/resources/MSC/2010/MSC2010
    Marking loose concept http://msc2010.org/resources/MSC/2010/00A35-formerly-1991 as top concept of scheme http://msc2010.org/resources/MSC/2010/MSC2010

Phase 8

Checking concept hierarchy
Phase 9

Checking labels
Warnings (561) show / hide full list

    Resource http://msc2010.org/resources/MSC/2010/26E10 has more than one prefLabel@None: choosing C∞-函数, 拟解析函数 (policy: shortest)
    Resource http://msc2010.org/resources/MSC/2010/55P43 has more than one prefLabel@None: choosing 具有附加结构的谱(E∞、A∞、环谱等) (policy: shortest)
    Resource http://msc2010.org/resources/MSC/2010/57M25 has more than one prefLabel@None: choosing Knots and links in SS (policy: shortest)

Phase 10

Writing output
